AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello

  Sample SAM Template for hello
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CreateLead:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Runtime: nodejs12.x
      Layers:
        - !Ref NodeJsLayer
      Handler: create.handler
      CodeUri: functions/leads_create
      MemorySize: 512
      Timeout: 300
      Tracing: Active
      Role:
        'Fn::GetAtt':
          - Role
          - Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref Map
        - LambdaInvokePolicy:
            FunctionName: !Ref Recommend
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt InsertLeadTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt LogLeadTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt LogLeadInTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ErrorNotificationTopic.TopicName
      Environment:
        Variables:
          ENV: !Ref Env
          TOPIC_INSERT_LEAD: !Ref InsertLeadTopic
          TOPIC_LOG_LEAD: !Ref LogLeadTopic
          TOPIC_LOG_LEAD_IN: !Ref LogLeadInTopic
          TOPIC_ERROR: !Ref ErrorNotificationTopic
          TOPIC_ROLLBAR: !Ref RollbarTopic
          FUNC_MAP: !Ref Map
          FUNC_RECOMMEND: !Ref Recommend
          REDSHIFT_ENDPOINT: !Ref RedshiftDBEndpoint
          REDSHIFT_DB_USER: !Ref RedshiftDBUser
          REDSHIFT_DB_NAME: !Ref RedshiftDBName
          REDSHIFT_DB_PORT: !Ref RedshiftDBPort
          BUCKET: !Ref ProPairBucketName
          VELOCIFY_URL: https://service.leads360.com/ClientService.asmx/
      VpcConfig: 
        SecurityGroupIds: 
          - sg-0b54841712c67143c
          - sg-0409e987266b33345
        SubnetIds: 
          - subnet-072fb25b65d0098f2
          - subnet-08702ed2157ee7951
  # HelloWorldFunction:
    # Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    # Properties:
      # CodeUri: functions/hello-world/
      # Handler: app.lambdaHandler
      # Runtime: nodejs14.x
      # Layers:
        # - !Ref NodeJsLayer
      # Architectures:
        # - x86_64
      # Events:
        # HelloWorld:
          # Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          # Properties:
            # Path: /hello
            # Method: get
    # Metadata:
      # BuildMethod: makefile
  NodeJsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/nodejs
      CompatibleRuntimes:
        - nodejs14.x
    Metadata:
      BuildMethod: makefile    
  # PythonLayer:
    # Type: AWS::Serverless::LayerVersion
    # Properties:
      # ContentUri: layers/python
      # CompatibleRuntimes:
        # - python2.7
    # Metadata:
      # BuildMethod: makefile    
  Python3Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/python3
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: makefile          
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn


