.PHONY: build-RepostLeads
build-RepostLeads:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-RepostLeadsScheduler
build-RepostLeadsScheduler:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 
