.PHONY: build-ReportRecommendations
build-ReportRecommendations:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-ReportEvents
build-ReportEvents:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-ReportSummaries
build-ReportSummaries:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-UpdateAthenaPartitions
build-UpdateAthenaPartitions:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-DailySREReport
build-DailySREReport:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 
