.PHONY: build-IndexBranches
build-IndexBranches:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-CreateBranch
build-CreateBranch:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-ShowBranch
build-ShowBranch:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-UpdateBranch
build-UpdateBranch:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 
