.PHONY: build-ProcessDirectMail
build-ProcessDirectMail:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-MailSentAudit
build-MailSentAudit:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 
