#! /bin/bash
export PYTHONPATH=`pwd`
export ENV=staging
export REDSHIFT_ENDPOINT=propair-rs.cbwhpsk1qhvp.us-west-1.redshift.amazonaws.com
export REDSHIFT_DB_NAME=staging
export REDSHIFT_DB_USER=stageuser
export REDSHIFT_DB_PORT=5439
export BUCKET=pro-pair-serverless-staging
export VELOCIFY=No
export TOPIC_ROLLBAR=arn:aws:sns:us-west-1:450889472107:pro-pair-serverless-staging-RollbarTopic-7H6UCD73I64I
. .py37/bin/activate