.PHONY: build-IndexAgents
build-IndexAgents:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-ShowAgent
build-ShowAgent:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-CreateAgent
build-CreateAgent:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-CreateAgents
build-CreateAgents:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-UpdateAgent
build-UpdateAgent:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 

.PHONY: build-UpdateAgents
build-UpdateAgents:
	cp *.js $(ARTIFACTS_DIR)
	cp *.json $(ARTIFACTS_DIR)
	cd $(ARTIFACTS_DIR) && npm install --production 
